### ISSUE TITLE
Provide more detailed instructions

### ISSUE THREAD

**Issue by shbach** [fvbommel/tasks2todotxt#1]
Hi, thanks for making this. Would you be able to provide more detailed instructions on how to use this? In particular, how to run this script. I don't know where to start. Much appreciated!

**Comment by fvbommel** [comment]
I've expanded the instructions in the [README](https://github.com/fvbommel/tasks2todotxt/blob/main/README.md). Does this help?

If not, where are you getting stuck?

**Comment by shbach** [comment]
Thanks! That was enough information for me to figure it out. To improve the documentation further, I think you can give an example of how to run it. e.g. `go run tasks2todotxt /path/to/json/auto.200922-0001-1.json /path/to/todo.txt`

I see some other issues with the exported file but I'll open separate issues for those.
